package:
  name: matplotlib
  version: 3.5.3
  tag:
    - min-scipy-stack
  top-level:
    - pylab
    - mpl_toolkits
    - matplotlib
source:
  url: https://files.pythonhosted.org/packages/02/81/e8276ec6ca005b3b2bfaaad0ea47dbb3a0e389ec8ab87d08e3ccbe4b2742/matplotlib-3.5.3.tar.gz
  sha256: 339cac48b80ddbc8bfd05daae0a3a73414651a8596904c2a881cfd1edb65f26c
  patches:
    - patches/0001-Disable-macOS-X-backend.patch
    - patches/0002-Disable-timer.patch
    - patches/0003-Hardcode-font-cache-path.patch
    - patches/0004-Adapt-to-NumPy-v2.patch # remove when upgrading to Matplotlib 3.8.4 or later
  extras:
    - - extras/setup.cfg
      - ./mplsetup.cfg

build:
  # RELOCATABLE flag is required because if affects how emscripten build ports.
  cflags: |
    -s RELOCATABLE=1
    -s USE_FREETYPE=1
    -s USE_LIBPNG=1
    -s USE_ZLIB=1
    -fexceptions
    -fno-lto
  cxxflags: |
    -std=c++14
    -fexceptions
  ldflags: |
    -fexceptions
  script: export SETUPTOOLS_SCM_PRETEND_VERSION=$PKG_VERSION
  post: |
    rm -rf matplotlib/backends/qt_editor
    rm -rf matplotlib/backends/web_backend
    rm -rf sphinxext
    cp $PKGDIR/extras/fontlist.json matplotlib
    cp $PKGDIR/extras/Humor-Sans-1.0.ttf matplotlib/mpl-data/fonts/ttf/Humor-Sans.ttf
    mkdir -p $PKGDIR/../../dist/fonts
    cp matplotlib/mpl-data/fonts/ttf/* $PKGDIR/../../dist/fonts/

requirements:
  host:
    - numpy
  run:
    - contourpy
    - cycler
    - fonttools
    - kiwisolver
    - numpy
    - packaging
    - Pillow
    - pyparsing
    - python-dateutil
    - pytz
    - matplotlib-pyodide

about:
  home: https://matplotlib.org
  PyPI: https://pypi.org/project/matplotlib
  summary: Python plotting package
  license: PSF
