package:
  name: astropy
  version: 6.1.4
  top-level:
    - astropy
source:
  url: https://files.pythonhosted.org/packages/13/25/adf5ee49f3990fc5cde050cce9c6f0a74a78af4eb18bd3aec8f1eecd1a26/astropy-6.1.4.tar.gz
  sha256: 361558e2b093a99bebe69f1fd47fac86a192607a4c16ed39ba0a800b2ab60c34
build:
  # The test module is imported from the top level `__init__.py`
  # so it cannot be unvendored
  unvendor-tests: false
  exports: requested # Astropy uses dlsym so we need to export more than just PyInit_astropy
  cflags: |
    -I $(HOSTSITEPACKAGES)/numpy/core/include
requirements:
  host:
    - packaging
    - numpy
  run:
    - packaging
    - numpy
    - pyerfa
    - pyyaml
    - astropy_iers_data
test:
  imports:
    - astropy
    - astropy.config
    - astropy.constants
    - astropy.convolution
    - astropy.coordinates
    - astropy.cosmology
    - astropy.extern
    - astropy.io
    - astropy.modeling
    - astropy.nddata
    - astropy.samp
    - astropy.stats
    - astropy.table
    - astropy.time
    - astropy.timeseries
    - astropy.uncertainty
    - astropy.units
    - astropy.utils
    - astropy.visualization
    - astropy.wcs
about:
  home: http://astropy.org
  PyPI: https://pypi.org/project/astropy
  summary: Astronomy and astrophysics core library
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - jobovy
